version: '3.2'

services:
  lofilibrarian:
    image: ghcr.io/iamcathal/lofilibrarian:latest
    container_name: lofilibrarian
    volumes:
      - ./logs/:/logs/
    ports:
      - '2946:2946'
    restart: on-failure

networks: 
  default: 
    external: 
      name: external-kr-network 